title: LCSecOps
description: Security research, lab walkthroughs, CTF writeups, and PNPT prep
url: "https://landocris.github.io"
baseurl: "/lcsecops"
author: Landon Crismas

theme: minima

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed               
